//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FileRenShell.rc
//
#define IDR_FILERENAMESHELL             100
#define IDD_RENAME_FILES_DIALOG         101
#define IDD_REPLACE_DIALOG              102
#define IDR_IMAGE_STRIP                 104
#define IDD_TOUCH_FILES_DIALOG          104
#define IDR_CONTEXT_MENU                105
#define IDD_CAPITALIZE_OPTIONS_PAGE     105
#define IDI_DETAILS                     109
#define IDD_OPTIONS_GENERAL_PAGE        110
#define IDC_FILE_RENAME_LIST            1000
#define IDC_FORMAT_COMBO                1001
#define IDC_SEQ_COUNT_EDIT              1002
#define IDC_COUNTER_LABEL               1003
#define IDC_DELIMITER_SET_COMBO         1004
#define IDC_COPY_SOURCE_PATHS_BUTTON    1005
#define IDC_PASTE_FILES_BUTTON          1006
#define IDC_CAPITALIZE_BUTTON           1007
#define IDC_CAPITALIZE_OPTIONS          1008
#define IDC_REPLACE_FILES_BUTTON        1009
#define IDC_SOURCE_FILES_GROUP          1010
#define IDC_DESTINATION_FILES_GROUP     1011
#define IDC_CLEAR_FILES_BUTTON          1012
#define IDC_TEXT_RADIO                  1013
#define IDC_CHARACTERS_RADIO            1014
#define IDC_MATCH_CASE_CHECK            1015
#define IDC_FORMAT_LEGEND_LABEL         1016
#define IDC_UNDO_BUTTON                 1017
#define IDC_REDO_BUTTON                 1018
#define IDC_REPLACE_DELIMS_BUTTON       1019
#define IDC_DELIMITER_STATIC            1020
#define IDC_NEW_DELIMITER_EDIT          1021
#define IDC_FIND_WHAT_COMBO             1022
#define IDC_REPLACE_WITH_COMBO          1023
#define IDC_EDITION_STATIC              1024
#define IDC_WORD_BREAK_CHARS_EDIT       1025
#define IDC_WORD_BREAK_PREFIXES_EDIT    1026
#define IDC_WORDS_PRESERVED_EDIT        1027
#define IDC_WORDS_UPPERCASE_EDIT        1028
#define IDC_WORDS_LOWERCASE_EDIT        1029
#define IDC_SET_DEFAULT_ALL             1030
#define IDC_UPPER_CASE_EXT_BUTTON       1031
#define IDC_CHANGE_CASE_BUTTON          1032
#define IDC_ARTICLES_EDIT               1033
#define IDC_ARTICLES_COMBO              1034
#define IDC_CONJUNCTIONS_EDIT           1035
#define IDC_CONJUNCTIONS_COMBO          1036
#define IDC_PREPOSITIONS_EDIT           1037
#define IDC_PREPOSITIONS_COMBO          1038
#define IDC_SKIP_NUMERIC_PREFIX_CHECK   1039
#define IDC_PICK_RENAME_ACTIONS         1040
#define IDC_STRIP_BAR_1                 1041
#define IDC_STRIP_BAR_2                 1042
#define IDC_FILE_TOUCH_LIST             1043
#define IDC_SHOW_SOURCE_INFO_CHECK      1044
#define IDC_MODIFIED_DATE               1045
#define IDC_CREATED_DATE                1046
#define IDC_ACCESSED_DATE               1047
#define IDC_ATTRIB_READONLY_CHECK       1048
#define IDC_ATTRIB_HIDDEN_CHECK         1049
#define IDC_ATTRIB_SYSTEM_CHECK         1050
#define IDC_ATTRIB_ARCHIVE_CHECK        1051
#define IDC_ATTRIB_DIRECTORY_CHECK      1052
#define IDC_ATTRIB_VOLUME_CHECK         1053
#define IDC_SMALL_ICON_SIZE_COMBO       1054
#define IDC_LARGE_ICON_SIZE_COMBO       1055
#define IDS_INVALID_FORMAT              5000
#define IDS_NO_DELIMITER_SET            5001
#define IDS_CHANGE_CASE_TAGS            5003
#define IDS_CASE_MODIFY_TAGS            5004
#define IDS_REPLACE_FILES_TIP_FORMAT    5005
#define ID_SEND_TO_CLIP                 32772
#define ID_NUMERIC_SEQUENCE_2DIGITS     32774
#define ID_NUMERIC_SEQUENCE_3DIGITS     32775
#define ID_NUMERIC_SEQUENCE_4DIGITS     32776
#define ID_NUMERIC_SEQUENCE_5DIGITS     32777
#define ID_NUMERIC_SEQUENCE             32778
#define ID_WILDCARD                     32779
#define ID_EXTENSION_SEPARATOR          32780
#define ID_RENAME_AND_COPY              32781
#define ID_SHELL_SUBMENU                32782
#define ID_SINGLE_WHITESPACE            32783
#define ID_REMOVE_WHITESPACE            32784
#define ID_DASH_TO_SPACE                32785
#define ID_SPACE_TO_DASH                32786
#define ID_UNDERBAR_TO_SPACE            32787
#define ID_SPACE_TO_UNDERBAR            32788
#define ID_TEXT_TITLE_CASE              32789
#define ID_TEXT_LOWER_CASE              32790
#define ID_TEXT_UPPER_CASE              32791
#define ID_TEXT_REPLACE_DELIMS          32792
#define ID_TEXT_SINGLE_WHITESPACE       32793
#define ID_TEXT_REMOVE_WHITESPACE       32794
#define ID_TEXT_DASH_TO_SPACE           32795
#define ID_TEXT_SPACE_TO_DASH           32796
#define ID_TEXT_UNDERBAR_TO_SPACE       32797
#define ID_TEXT_SPACE_TO_UNDERBAR       32798
#define ID_PARENT_FOLDER                32799
#define ID_PICK_FILENAME                32800
#define ID_PICK_DIR_PATH                32801
#define ID_COPY_FIND_TO_REPLACE         32802
#define ID_PICK_FORMAT_TOKEN            32803
#define ID_PICK_TEXT_TOOLS              32804
#define ID_TOGGLE_AUTO_GENERATE         32805
#define ID_ENSURE_UNIFORM_NUM_PADDING   32806
#define ID_SEQ_COUNT_RESET              32807
#define ID_SEQ_COUNT_FIND_NEXT          32808
#define ID_SEQ_COUNT_AUTO_ADVANCE       32809
#define ID_TOUCH_FILES                  32810
#define ID_COPY_MODIFIED_DATE           32811
#define ID_COPY_CREATED_DATE            32812
#define ID_COPY_ACCESSED_DATE           32813
#define ID_PUSH_TO_ATTRIBUTE_FIELDS     32814
#define ID_PUSH_TO_ALL_FIELDS           32815

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           5004
#endif
#endif
