#pragma once

#include "utl/utl_base.h"			// UTL_BASE library classes
#include "utl/UI/utl_ui.h"			// UTL_UI library classes

// MFC stuff not actually used in this project:
//#include <afxdisp.h>				// MFC Automation classes
//#include <afxdtctl.h>           	// MFC support for Internet Explorer 4 Common Controls
//#include <afxcontrolbars.h>     	// MFC support for ribbons and control bars


#ifdef _DEBUG
	#define USE_UT		// no UT code in release builds
#endif // _DEBUG


/* Generated by VC 17 (VS-2022)

#ifdef _UNICODE
#if defined _M_IX86
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='x86' publicKeyToken='6595b64144ccf1df' language='*'\"")
#elif defined _M_X64
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='amd64' publicKeyToken='6595b64144ccf1df' language='*'\"")
#else
#pragma comment(linker,"/manifestdependency:\"type='win32' name='Microsoft.Windows.Common-Controls' version='6.0.0.0' processorArchitecture='*' publicKeyToken='6595b64144ccf1df' language='*'\"")
#endif
#endif

*/
