//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Slider.rc
//
#define IDD_ALBUMDIALOGBAR              106
#define IDR_MAINFRAME                   128
#define IDR_ALBUMTYPE                   129
#define IDR_IMAGETYPE                   130
#define IDR_IMAGEVIEW                   141
#define IDD_WORKSPACE_DIALOG            142
#define IDR_COMMAND_BAR_ACCEL           143
#define IDR_CONTEXT_MENU                149
#define IDD_ALBUM_SETTINGS_DIALOG       150
#define IDD_SEARCH_SPEC_DIALOG          151
#define IDR_ALBUM_DLG_ACCEL             152
#define IDR_ALBUM_DLG_SEARCH_SPEC_ACCEL 153
#define IDR_ALBUMTYPE_NAV               159
#define IDD_FILE_MOVE_DIALOG            161
#define IDD_LOGGER_DIALOG               162
#define IDD_LAYOUT_DIALOG               166
#define IDD_UNDO_REDO_DIALOG            168
#define IDD_INPUT_PASSWORD_DIALOG       171
#define IDR_APP_TOOL_STRIP              174
#define IDD_ARCHIVE_IMAGES_DIALOG       201
#define IDC_FILE_PATHS_LIST             201
#define IDD_DEFINE_PASSWORD_DIALOG      202
#define IDC_FORMAT_COMBO                203
#define IDC_COUNTER_EDIT                204
#define IDC_SEARCH_FOLDER_COMBO         1001
#define IDC_BROWSE_FOLDER_BUTTON        1002
#define IDC_SEARCH_FILTERS_COMBO        1003
#define IDC_BROWSE_FILE_BUTTON          1004
#define IDC_FOUND_FILES_LIST            1006
#define IDC_RECURSE_CHECK               1007
#define CK_AUTOSAVE                     1007
#define CK_PERSIST_OPEN_DOCS            1008
#define IDC_SCROLL_POS_EDIT             1009
#define IDC_CURR_FILE_EDIT              1010
#define CK_SHOW_NAVDIALOG_BAR           1010
#define IDC_SCROLL_POS_SPIN             1011
#define IDC_NAV_COUNT_STATIC            1013
#define IDC_PLAY_DELAY_COMBO            1014
#define IDC_SEARCH_SPEC_LIST            1016
#define CM_ADD_SEARCH_SPEC              1017
#define CM_MODIFY_SEARCH_SPEC           1018
#define CM_DELETE_SEARCH_SPEC           1019
#define CM_MOVE_UP_SEARCH_SPEC          1020
#define CM_MOVE_DOWN_SEARCH_SPEC        1021
#define IDC_MIN_FILE_SIZE_CHECK         1022
#define IDC_MIN_FILE_SIZE_EDIT          1023
#define IDC_MAX_FILE_SIZE_CHECK         1025
#define IDC_MAX_FILE_SIZE_EDIT          1026
#define IDC_FOUND_FILES_LISTVIEW        1028
#define IDC_LIST_ORDER_COMBO            1029
#define CM_SEARCH_FOR_FILES             1030
#define IDC_OPEN_IMAGE                  1031
#define IDC_EXPLORE_IMAGE               1032
#define IDC_MAX_MRU_COUNT_EDIT          1033
#define IDC_DEST_FOLDER_COMBO           1036
#define IDC_SOURCE_EDIT                 1037
#define IDC_BROWSE_DEST_FOLDER_BUTTON   1038
#define IDC_LOGGER_COMBO                1041
#define CK_LOGGER_ENABLED               1042
#define CK_PREPEND_TIMESTAMP            1043
#define IDC_VIEW_LOG_FILE_BUTTON        1044
#define IDC_CLEAR_LOG_FILE_BUTTON       1045
#define IDC_CLEAR_THUMB_CACHE_BUTTON    1048
#define IDC_THUMB_COL_COUNT_EDIT        1050
#define IDC_FOUND_FILES_STATIC          1053
#define IDC_SEARCH_SPEC_STATIC          1054
#define IDC_FOUND_FILES_GAP             1055
#define IDC_LIST_ORDER_STATIC           1056
#define IDC_THUMB_PREVIEW_STATIC        1057
#define IDC_AUTO_DROP_CHECK             1059
#define IDC_SEARCH_OPTIONS_COMBO        1060
#define IDC_AUTO_REGENERATE_CHECK       1061
#define IDC_STACK_STEP_LIST             1064
#define IDC_DEST_DIR_PATH_EDIT          1067
#define IDC_COPY_FILES_RADIO            1068
#define IDC_RENAME_FILES_RADIO          1069
#define CM_CREATE_DEST_FOLDER           1070
#define IDC_SAVECUSTOMORDERUNDOREDO_CHECK 1071
#define IDC_TO_FOLDER_RADIO             1074
#define IDC_TO_COMPOUND_FILE_RADIO      1075
#define IDC_ALLOW_EMBEDDED_FILE_TRANFERS_CHECK 1076
#define IDC_SELECTED_FILES_RADIO        1077
#define IDC_ALL_FILES_RADIO             1078
#define IDC_RESETNUMCOUNTER_BUTTON      1079
#define IDC_TARGET_FILE_COUNT_STATIC    1080
#define IDC_TARGET_GROUP                1081
#define IDC_PASSWORD_EDIT               1082
#define IDC_FILE_PROTECTED_STATIC       1083
#define IDC_CONFIRM_PASSWORD_EDIT       1084
#define CK_PERSIST_ALBUM_IMAGE_STATE    1084
#define IDC_PREFIX_DEEP_STREAM_NAMES_CHECK 1085
#define IDC_VISTA_STYLE_FILE_DLG_CHECK  1086
#define IDC_ENLARGE_SMOOTHING_CHECK     1087
#define IDC_AUTO_REGEN_SMALL_STG_THUMBS_CHECK 1088
#define IDC_THUMB_BOUNDS_SIZE_COMBO     1089
#define IDC_DEFAULT_SLIDE_DELAY_COMBO   1090
#define IDS_ERROR_CANNOTEXPLORE         2001
#define IDS_ERROR_NOSELECTION           2002
#define IDS_DROPONLYONEFOLDER           2003
#define IDS_PROMPT_KEEPTHUMBFILE        2004
#define IDS_PROMPT_CORRUPTTHUMBFILE     2005
#define IDS_ERROR_INVALID_DEST_DIR      2006
#define IDS_PROMPT_SWITCHTOCUSTOMORDER  2007
#define IDS_ERROR_FILE_COMMIT           2008
#define IDS_PROMPT_INVALID_FOLDER       2009
#define IDS_PROMPT_REGENERATE_ALBUM     2010
#define IDS_PROMPT_CANT_CREATE_DEST_FOLDER 2011
#define IDS_PROMPT_CREATED_DEST_FOLDER  2012
#define IDS_PROMPT_COPYMOVEFILEOP       2013
#define IDS_FORMAT_PARSING_ERROR        2014
#define IDS_UNDOREDO_INVALID_FILE_PAIRS 2015
#define IDS_OVERWRITE_PROMPT            2016
#define IDS_INVALID_FORMAT_FMT          2017
#define IDS_PROMPT_FILE_OP              2018
#define IDS_SLIDE_ALBUM_FILTER_SPEC     3001
#define IDS_ARCHIVE_STG_FILTER_SPEC     3002
#define IDS_DELETE_ATTR_PROMPT          3011
#define IDS_REPLACE_DUP_PROMPT          3012
#define IDS_HELP_MESSAGE                3013
#define IDS_NO_DIR_SEARCH_SPEC          3016
#define IDW_SB_PROGRESS_CAPTION         32771
#define IDW_SB_PROGRESS_BAR             32772
#define IDW_AUTO_IMAGE_SIZE_COMBO       32773
#define IDW_ZOOM_COMBO                  32774
#define IDW_NAV_SLIDER                  32775
#define IDW_SMOOTHING_MODE_CHECK        32776
#define CM_ESCAPE_KEY                   32777
#define CM_MDI_CLOSE_ALL                32778
#define CM_MDI_WINDOWS                  32779
#define ID_VIEW_ALBUMDIALOGBAR          32780
#define CM_IMAGE_SIZE_AUTO_FIT_LARGE    32781
#define CM_IMAGE_SIZE_AUTO_FIT_ALL      32782
#define CM_IMAGE_SIZE_FIT_WIDTH         32783
#define CM_IMAGE_SIZE_FIT_HEIGHT        32784
#define CM_IMAGE_SIZE_ACTUAL_SIZE       32785
#define CM_IMAGE_SIZE_USE_ZOOM_PCT      32786
#define CM_FOCUS_ZOOM                   32790
#define CM_ZOOM_NORMAL                  32791
#define CM_ZOOM_IN                      32792
#define CM_ZOOM_OUT                     32793
#define CM_RESIZE_VIEW_TO_FIT           32794
#define CM_EDIT_ALBUM                   32795
#define CM_NAV_PLAY                     32796
#define CM_NAV_DIR_FWD                  32797
#define CM_NAV_DIR_REV                  32798
#define CM_NAV_BEGIN                    32799
#define CM_NAV_PREV                     32800
#define CM_NAV_NEXT                     32801
#define CM_NAV_END                      32802
#define CM_NAV_LEFT                     32803
#define CM_NAV_RIGHT                    32804
#define CM_NAV_PREV_PAGE                32805
#define CM_NAV_NEXT_PAGE                32806
#define CM_SCROLL_LEFT                  32807
#define CM_SCROLL_RIGHT                 32808
#define CM_SCROLL_UP                    32809
#define CM_SCROLL_DOWN                  32810
#define CM_SCROLL_PAGE_LEFT             32811
#define CM_SCROLL_PAGE_RIGHT            32812
#define CM_SCROLL_PAGE_UP               32813
#define CM_SCROLL_PAGE_DOWN             32814
#define CM_NAV_CIRCULAR                 32815
#define CM_SAVE_WORKSPACE               32816
#define CM_EDIT_WORKSPACE               32817
#define CM_LOAD_WORKSPACE_DOCS          32818
#define CM_NAV_SCROLL_BAR               32820
#define CK_FULL_SCREEN                  32821
#define CM_TOGGLE_MAXIMIZE              32822
#define CM_EDIT_BK_COLOR                32823
#define CM_FOCUS_SLIDER                 32824
#define CM_EDIT_IMAGE_SEL_COLOR         32825
#define CK_SHOW_THUMB_VIEW              32827
#define CM_OPEN_IMAGE_FILE              32828
#define CM_DELETE_FILE                  32829
#define CM_DELETE_FILE_NO_UNDO          32830
#define CM_MOVE_FILE                    32831
#define CM_EXPLORE_IMAGE                32832
#define CM_EDIT_IMAGE_SEL_TEXT_COLOR    32833
#define CM_LOGGER_OPTIONS               32834
#define CM_TOGGLE_SIBLING_VIEW          32835
#define CM_CLEAR_IMAGE_CACHE            32836
#define CM_REFRESH_CONTENT              32837
#define CM_DROP_MOVE_IMAGE              32838
#define CM_DROP_COPY_IMAGE              32839
#define CM_CANCEL_DROP                  32840
#define CM_AUTO_DROP_DEFRAGMENT         32841
#define CM_AUTO_DROP_UNDO               32842
#define CM_AUTO_DROP_REDO               32843
#define CM_AUTO_DROP_CLEAR_UNDO_REDO_STACKS 32844
#define CM_REGENERATE_ALBUM             32845
#define CM_IS_AUTO_DROP                 32846
#define CM_ARCHIVE_IMAGES               32847
#define CM_CUSTOM_ORDER_UNDO            32848
#define CM_CUSTOM_ORDER_REDO            32849
#define CM_CLEAR_CUSTOM_ORDER_UNDO_REDO_STACKS 32850
#define CK_SAVE_CU_UNDO_REDO_BUFFER     32851
#define CM_SELECT_ALL_THUMBS            32852
#define CM_CLEAR_TEMP_EMBEDDED_CLONES   32853
#define ID_FILE_OPEN_ALBUM_FOLDER       32854
#define ID_EDIT_ARCHIVE_PASSWORD        32855
#define ID_ORDER_ORIGINAL               32856
#define ID_ORDER_CUSTOM                 32857
#define ID_ORDER_RANDOM_SHUFFLE         32858
#define ID_ORDER_RANDOM_SHUFFLE_SAME_SEED 32859
#define ID_ORDER_BY_FULL_PATH_ASC       32860
#define ID_ORDER_BY_FULL_PATH_DESC      32861
#define ID_ORDER_BY_DIMENSION_ASC       32862
#define ID_ORDER_BY_DIMENSION_DESC      32863

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32879
#define _APS_NEXT_CONTROL_VALUE         1092
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
