//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Slider.rc
//
#define IDD_ALBUMDIALOGBAR              106
#define IDR_MAINFRAME                   128
#define IDR_ALBUMTYPE                   129
#define IDR_IMAGETYPE                   130
#define IDR_IMAGEVIEW                   141
#define IDD_WORKSPACE_DIALOG            142
#define IDR_COMMAND_BAR_ACCEL           143
#define IDR_CONTEXT_MENU                149
#define IDD_ALBUM_SETTINGS_DIALOG       150
#define IDD_SEARCH_PATTERN_DIALOG       151
#define IDR_ALBUMTYPE_NAV               159
#define IDD_FILE_MOVE_DIALOG            161
#define IDD_LOGGER_DIALOG               162
#define IDD_LAYOUT_DIALOG               166
#define IDD_UNDO_REDO_DIALOG            168
#define IDR_APP_TOOL_STRIP              169
#define IDD_ARCHIVE_IMAGES_DIALOG       201
#define IDC_FILE_PATHS_LIST             201
#define IDC_FORMAT_COMBO                203
#define IDC_COUNTER_EDIT                204
#define IDC_SEARCH_PATH_COMBO           1001
#define IDC_SEARCH_FILTERS_COMBO        1002
#define IDC_SEARCH_MODE_COMBO           1003
#define IDC_FOUND_FILES_LIST            1006
#define IDC_RECURSE_CHECK               1007
#define IDC_AUTOSAVE_CHECK              1007
#define IDC_PERSIST_OPEN_DOCS_CHECK     1008
#define IDC_SEEK_CURR_POS_EDIT          1009
#define IDC_CURR_FILE_EDIT              1010
#define IDC_SCROLL_POS_SPIN             1011
#define IDC_NAV_COUNT_STATIC            1013
#define IDC_PLAY_DELAY_COMBO            1014
#define IDC_PATTERNS_LISTVIEW           1015
#define IDC_MIN_FILE_SIZE_CHECK         1022
#define IDC_MIN_FILE_SIZE_EDIT          1023
#define IDC_MAX_FILE_SIZE_CHECK         1025
#define IDC_MAX_FILE_SIZE_EDIT          1026
#define IDC_MAX_FILE_COUNT_CHECK        1027
#define IDC_FOUND_IMAGES_LISTVIEW       1028
#define IDC_LIST_ORDER_COMBO            1029
#define IDC_SEARCH_FOR_FILES            1030
#define IDC_MAX_FILE_COUNT_EDIT         1030
#define IDC_OPEN_IMAGE                  1031
#define IDC_EXPLORE_IMAGE               1032
#define IDC_MAX_MRU_COUNT_EDIT          1033
#define IDC_DEST_FOLDER_COMBO           1036
#define IDC_SOURCE_EDIT                 1037
#define IDC_BROWSE_DEST_FOLDER_BUTTON   1038
#define IDC_LOGGER_COMBO                1041
#define IDC_LOGGER_ENABLED_CHECK        1042
#define IDC_TIMESTAMP_PREFIX_CHECK      1043
#define IDC_VIEW_LOG_FILE_BUTTON        1044
#define IDC_CLEAR_LOG_FILE_BUTTON       1045
#define IDC_CLEAR_THUMB_CACHE_BUTTON    1048
#define IDC_THUMB_COL_COUNT_EDIT        1050
#define IDC_FOUND_FILES_STATIC          1053
#define IDC_LIST_ORDER_STATIC           1056
#define IDC_THUMB_PREVIEW_STATIC        1057
#define IDC_AUTO_DROP_CHECK             1059
#define IDC_AUTO_REGENERATE_CHECK       1061
#define IDC_STACK_STEP_LIST             1064
#define IDC_DEST_DIR_PATH_EDIT          1067
#define IDC_COPY_FILES_RADIO            1068
#define IDC_RENAME_FILES_RADIO          1069
#define IDC_CREATE_DEST_FOLDER          1070
#define IDC_SAVECUSTOMORDERUNDOREDO_CHECK 1071
#define IDC_TO_FOLDER_RADIO             1074
#define IDC_TO_COMPOUND_FILE_RADIO      1075
#define IDC_ALLOW_EMBEDDED_FILE_TRANFERS_CHECK 1076
#define IDC_SELECTED_FILES_RADIO        1077
#define IDC_ALL_FILES_RADIO             1078
#define IDC_RESETNUMCOUNTER_BUTTON      1079
#define IDC_TARGET_FILE_COUNT_STATIC    1080
#define IDC_TARGET_GROUP                1081
#define IDC_PERSIST_ALBUM_IMAGE_STATE_CHECK 1084
#define IDC_PREFIX_DEEP_STREAM_NAMES_CHECK 1085
#define IDC_VISTA_STYLE_FILE_DLG_CHECK  1086
#define IDC_ENLARGE_SMOOTHING_CHECK     1087
#define IDC_AUTO_REGEN_SMALL_STG_THUMBS_CHECK 1088
#define IDC_THUMB_BOUNDS_SIZE_COMBO     1089
#define IDC_DEFAULT_SLIDE_DELAY_COMBO   1090
#define IDC_DOC_VERSION_LABEL           1092
#define IDC_DOC_VERSION_STATIC          1093
#define IDS_ERROR_CANNOTEXPLORE         2001
#define IDS_ERROR_NOSELECTION           2002
#define IDS_DROPONLYONEFOLDER           2003
#define IDS_PROMPT_KEEPTHUMBFILE        2004
#define IDS_PROMPT_CORRUPTTHUMBFILE     2005
#define IDS_ERROR_INVALID_DEST_DIR      2006
#define IDS_PROMPT_SWITCHTOCUSTOMORDER  2007
#define IDS_ERROR_FILE_COMMIT           2008
#define IDS_PROMPT_INVALID_FOLDER       2009
#define IDS_PROMPT_REGENERATE_ALBUM     2010
#define IDS_PROMPT_CANT_CREATE_DEST_FOLDER 2011
#define IDS_PROMPT_CREATED_DEST_FOLDER  2012
#define IDS_PROMPT_COPYMOVEFILEOP       2013
#define IDS_FORMAT_PARSING_ERROR        2014
#define IDS_UNDOREDO_INVALID_FILE_PAIRS 2015
#define IDS_OVERWRITE_PROMPT            2016
#define IDS_INVALID_FORMAT_FMT          2017
#define IDS_PROMPT_FILE_OP              2018
#define IDS_SLIDE_ALBUM_FILTER_SPEC     3001
#define IDS_ARCHIVE_STG_FILTER_SPEC     3002
#define IDS_DELETE_ATTR_PROMPT          3011
#define IDS_HELP_MESSAGE                3013
#define IDS_NO_DIR_SEARCH_SPEC          3016
#define ID_SKIP_IMAGE_DIM_EVALUATION_CMDLINK 3017
#define ID_KEEP_IMAGE_DIM_EVALUATION_CMDLINK 3018
#define IDW_SB_PROGRESS_CAPTION         32771
#define IDW_SB_PROGRESS_BAR             32772
#define IDW_IMAGE_SCALING_COMBO         32773
#define IDW_ZOOM_COMBO                  32774
#define IDW_NAVIG_SLIDER_CTRL           32775
#define IDW_SMOOTHING_MODE_CHECK        32776
#define ID_CM_ESCAPE_KEY                32777
#define ID_CM_MDI_CLOSE_ALL             32778
#define ID_VIEW_ALBUMDIALOGBAR          32780
#define ID_TOGGLE_SCALING_AUTO_FIT_LARGE 32781
#define ID_TOGGLE_SCALING_AUTO_FIT_ALL  32782
#define ID_TOGGLE_SCALING_FIT_WIDTH     32783
#define ID_TOGGLE_SCALING_FIT_HEIGHT    32784
#define ID_TOGGLE_SCALING_ACTUAL_SIZE   32785
#define ID_TOGGLE_SCALING_USE_ZOOM_PCT  32786
#define ID_FOCUS_ON_ZOOM_COMBO          32789
#define ID_FOCUS_ON_SLIDER_CTRL         32790
#define ID_ZOOM_NORMAL_100              32791
#define ID_ZOOM_IN                      32792
#define ID_ZOOM_OUT                     32793
#define ID_RESIZE_VIEW_TO_FIT           32794
#define ID_EDIT_ALBUM                   32795
#define ID_TOGGLE_NAVIG_PLAY            32796
#define ID_TOGGLE_NAVIG_DIR_FWD         32797
#define ID_TOGGLE_NAVIG_DIR_REV         32798
#define ID_TOGGLE_NAVIG_WRAP_MODE       32799
#define ID_NAVIG_SEEK_PREV              32800
#define ID_NAVIG_SEEK_NEXT              32801
#define ID_NAVIG_SEEK_FIRST             32802
#define ID_NAVIG_SEEK_LAST              32803
#define ID_NAVIG_SEEK_LEFT              32804
#define ID_NAVIG_SEEK_RIGHT             32805
#define ID_NAVIG_SEEK_PREV_PAGE         32806
#define ID_NAVIG_SEEK_NEXT_PAGE         32807
#define CM_SCROLL_LEFT                  32807
#define CM_SCROLL_RIGHT                 32808
#define CM_SCROLL_UP                    32809
#define CM_SCROLL_DOWN                  32810
#define CM_SCROLL_PAGE_LEFT             32811
#define CM_SCROLL_PAGE_RIGHT            32812
#define CM_SCROLL_PAGE_UP               32813
#define CM_SCROLL_PAGE_DOWN             32814
#define CM_SAVE_WORKSPACE               32816
#define CM_EDIT_WORKSPACE               32817
#define CM_LOAD_WORKSPACE_DOCS          32818
#define CK_FULL_SCREEN                  32821
#define CM_TOGGLE_MAXIMIZE              32822
#define ID_EDIT_BK_COLOR                32823
#define CM_EDIT_IMAGE_SEL_COLOR         32825
#define CK_SHOW_THUMB_VIEW              32827
#define CM_OPEN_IMAGE_FILE              32828
#define CM_DELETE_FILE                  32829
#define CM_DELETE_FILE_NO_UNDO          32830
#define CM_MOVE_FILE                    32831
#define CM_EXPLORE_IMAGE                32832
#define CM_EDIT_IMAGE_SEL_TEXT_COLOR    32833
#define CM_LOGGER_OPTIONS               32834
#define CM_TOGGLE_SIBLING_VIEW          32835
#define CM_CLEAR_IMAGE_CACHE            32836
#define CM_REFRESH_CONTENT              32837
#define CM_DROP_MOVE_IMAGE              32838
#define CM_DROP_COPY_IMAGE              32839
#define CM_CANCEL_DROP                  32840
#define CM_AUTO_DROP_DEFRAGMENT         32841
#define CM_AUTO_DROP_UNDO               32842
#define CM_AUTO_DROP_REDO               32843
#define CM_AUTO_DROP_CLEAR_UNDO_REDO_STACKS 32844
#define CM_REGENERATE_ALBUM             32845
#define CM_IS_AUTO_DROP                 32846
#define CM_ARCHIVE_IMAGES               32847
#define CM_CUSTOM_ORDER_UNDO            32848
#define CM_CUSTOM_ORDER_REDO            32849
#define CM_CLEAR_CUSTOM_ORDER_UNDO_REDO_STACKS 32850
#define CK_SAVE_CU_UNDO_REDO_BUFFER     32851
#define CM_SELECT_ALL_THUMBS            32852
#define CM_CLEAR_TEMP_EMBEDDED_CLONES   32853
#define ID_FILE_OPEN_ALBUM_FOLDER       32854
#define ID_EDIT_ARCHIVE_PASSWORD        32855
#define ID_ORDER_ORIGINAL               32856
#define ID_ORDER_CUSTOM                 32857
#define ID_ORDER_RANDOM_SHUFFLE         32858
#define ID_ORDER_RANDOM_SHUFFLE_SAME_SEED 32859
#define ID_ORDER_BY_FULL_PATH_ASC       32860
#define ID_ORDER_BY_FULL_PATH_DESC      32861
#define ID_ORDER_BY_DIMENSION_ASC       32862
#define ID_ORDER_BY_DIMENSION_DESC      32863

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32882
#define _APS_NEXT_CONTROL_VALUE         1094
#define _APS_NEXT_SYMED_VALUE           3019
#endif
#endif
