//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Wintruder.rc
//
#define IDD_MAIN_DIALOG                 101
#define IDD_GENERAL_PAGE                102
#define IDD_TREE_WND_PAGE               103
#define IDD_OPTIONS_PAGE                104
#define IDD_EDIT_CAPTION_PAGE           105
#define IDD_EDIT_IDENT_PAGE             106
#define IDD_EDIT_FLAGS_PAGE             107
#define IDD_EDIT_PLACEMENT_PAGE         108
#define IDD_FLAG_LIST_PAGE              109
#define IDD_FIND_WND_DIALOG             110
#define IDD_APPLY_CHANGES_DIALOG        111
#define IDR_IMAGE_STRIP                 112
#define IDR_WND_TYPES_STRIP             113
#define IDR_CONTEXT_MENU                114
#define IDR_POINTER_CURSOR              115
#define IDR_MAIN_SHARED_ACCEL           122
#define IDR_FLAGS_CONTROL_ACCEL         123
#define IDI_APP_SMALL_ICON              140
#define IDC_MAIN_SHEET                  1000
#define IDC_DETAILS_SHEET               1001
#define IDC_TRACK_TOOL_ICON             1002
#define IDC_TRACKING_POS_STATIC         1003
#define IDC_EXPAND_DETAILS              1004
#define IDC_BRIEF_INFO_EDIT             1005
#define IDC_WINDOW_DETAILS_GROUP        1006
#define IDC_BUILD_INFO_STATIC           1007
#define IDC_HANDLE_EDIT                 1008
#define IDC_WCLASS_COMBO                1009
#define IDC_CAPTION_EDIT                1010
#define IDC_ID_EDIT                     1011
#define IDC_FROM_BEGINING_RADIO         1012
#define IDC_FROM_CURRENT_RADIO          1013
#define IDC_DIR_FORWARD_RADIO           1014
#define IDC_DIR_BACKWARD_RADIO          1015
#define IDC_MATCH_CASE_CHECK            1016
#define IDC_MATCH_WHOLE_CHECK           1017
#define IDC_RESET_DEFAULT               1018
#define IDC_REFRESH_NOW                 1019
#define IDC_QUESTION_ICON               1020
#define IDC_PROMPT_STATIC               1021
#define IDC_CHANGED_FIELDS_STATIC       1022
#define IDC_USE_SETWINDOWPOS_CHECK      1023
#define IDC_SWP_DRAWFRAME_CHECK         1024
#define IDC_SWP_FRAMECHANGED_CHECK      1025
#define IDC_SWP_NOREDRAW_CHECK          1026
#define IDC_SWP_NOACTIVATE_CHECK        1027
#define IDC_SWP_SHOWWINDOW_CHECK        1028
#define IDC_SWP_HIDEWINDOW_CHECK        1029
#define IDC_GENERAL_INFO_EDIT           1030
#define IDC_FIELD_EDIT_BUTTON           1031
#define IDC_WINDOW_TREE                 1032
#define IDC_EDIT_CAPTION_EDIT           1047
#define IDC_IDENT_DEC_LABEL             1048
#define IDC_IDENT_DEC_EDIT              1049
#define IDC_IDENT_DEC_SPIN              1050
#define IDC_IDENT_HEX_LABEL             1051
#define IDC_IDENT_HEX_EDIT              1052
#define IDC_IDENT_LITERAL_COMBO         1053
#define IDC_TOTAL_FLAGS_EDIT            1054
#define IDC_UNKNOWN_FLAGS_LABEL         1055
#define IDC_UNKNOWN_FLAGS_EDIT          1056
#define IDC_FLAGS_EDITOR_LIST           1057
#define IDC_ORG_X_EDIT                  1062
#define IDC_ORG_Y_EDIT                  1063
#define IDC_WIDTH_EDIT                  1064
#define IDC_HEIGHT_EDIT                 1065
#define IDC_LEFT_EDIT                   1066
#define IDC_TOP_EDIT                    1067
#define IDC_RIGHT_EDIT                  1068
#define IDC_BOTTOM_EDIT                 1069
#define IDC_ORG_X_SPIN                  1070
#define IDC_ORG_Y_SPIN                  1071
#define IDC_WIDTH_SPIN                  1072
#define IDC_HEIGHT_SPIN                 1073
#define IDC_LEFT_SPIN                   1074
#define IDC_TOP_SPIN                    1075
#define IDC_RIGHT_SPIN                  1076
#define IDC_BOTTOM_SPIN                 1077
#define IDC_AUTO_APPLY_PLACEMENT_CHECK  1078
#define IDS_WND_EXPIRED_FMT             5000
#define IDS_WND_NOT_FOUND               5001
#define IDS_EDIT_STYLE_PAGE             5002
#define IDS_EDIT_STYLE_EX_PAGE          5003
#define IDS_STYLE_PROMPTTITLE           5004
#define IDS_STYLE_EX_PROMPTTITLE        5005
#define IDS_CAPTION_PROMPTTITLE         5006
#define IDS_IDENT_PROMPTTITLE           5007
#define IDS_PLACE_PROMPTTITLE           5008
#define ID_TOP_MOST_CHECK               10000
#define ID_AUTO_HIDE_CHECK              10001
#define ID_AUTO_HILIGHT_CHECK           10002
#define ID_FRAME_STYLE_COMBO            10003
#define ID_FRAME_SIZE_EDIT              10004
#define ID_QUERY_WND_ICONS_COMBO        10005
#define ID_IGNORE_HIDDEN_CHECK          10006
#define ID_IGNORE_DISABLED_CHECK        10007
#define ID_DISPLAY_ZERO_FLAGS_CHECK     10008
#define ID_AUTO_UPDATE_CHECK            10009
#define ID_AUTO_UPDATE_REFRESH_CHECK    10010
#define ID_AUTO_UPDATE_TIMEOUT_EDIT     10011
#define ID_AUTO_UPDATE_TARGET_COMBO     10012
#define ID_MOVE_TOOL                    10013
#define ID_SIZE_TOOL                    10014
#define ID_SIZE_TOP_LEFT_TOOL           10015
#define ID_SIZE_BOTTOM_RIGHT_TOOL       10016
#define ID_COPY_TREE_ANCESTORS          10017
#define ID_COPY_TREE_CHILDREN           10018
#define CM_MINIMIZE                     11000
#define CM_VIEW_GENERAL                 11001
#define CM_VIEW_WND_TREE                11002
#define CM_VIEW_OPTIONS                 11003
#define CM_EDIT_CAPTION                 11004
#define CM_EDIT_IDENT                   11005
#define CM_EDIT_STYLE                   11006
#define CM_EDIT_STYLE_EX                11007
#define CM_EDIT_PLACE                   11008
#define CM_HIGHLIGHT_WINDOW             11009
#define CM_REFRESH                      11010
#define CM_REFRESH_BRANCH               11011
#define CM_FIND_WINDOW                  11012
#define CM_FIND_NEXT_WINDOW             11013
#define CM_FIND_PREV_WINDOW             11014
#define CM_UPDATE_TICK                  11015
#define CM_EXPAND_BRANCH                11016
#define CM_COLAPSE_BRANCH               11017
#define CM_RESTORE                      11018
#define CM_COPY_TARGET_WND              11019
#define CM_COPY_WND_CLASS               11020
#define CM_COPY_WND_CAPTION             11021
#define CM_COPY_WND_IDENT               11022
#define CM_ACTIVATE_WINDOW              11023
#define CM_SHOW_WINDOW                  11024
#define CM_HIDE_WINDOW                  11025
#define CM_TOGGLE_TOPMOST_WINDOW        11026
#define CM_TOGGLE_ENABLE_WINDOW         11027
#define CM_REDRAW_DESKTOP               11028
#define CM_MOVE_WINDOW_UP               11029
#define CM_MOVE_WINDOW_DOWN             11030
#define CM_MOVE_WINDOW_TO_TOP           11031
#define CM_MOVE_WINDOW_TO_BOTTOM        11032
#define CM_COPY_FORMATTED               11033
#define CM_COPY_SELECTED                11034

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         10019
#define _APS_NEXT_CONTROL_VALUE         1080
#define _APS_NEXT_SYMED_VALUE           5009
#endif
#endif
