//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by DemoUtl.rc
//
#define IDD_DEMO_FORM                   101
#define IDD_DEMO_DIALOG                 102
#define IDR_LOW_COLOR_STRIP             103
#define IDR_MAINFRAME                   128
#define IDR_TEST_DOC_TYPE               129
#define IDR_FORMAT_PICKER_MENU          130
#define IDD_LIST_PAGE                   134
#define IDD_EDIT_PAGE                   135
#define IDD_DETAILS_PAGE                136
#define IDR_IMAGE_STRIP                 139
#define IDD_IMAGE_DIALOG                140
#define IDD_IMAGE_PAGE_EMPTY            141
#define IDD_IMAGE_PAGE_ALPHA_BLEND      142
#define IDD_IMAGE_PAGE_BLEND_COLOR      143
#define IDD_IMAGE_PAGE_DISABLED         144
#define IDR_CONTEXT_MENU                144
#define IDD_IMAGE_PAGE_CONVERT_IMAGE    145
#define IDD_IMAGE_PAGE_SHOW_IMAGE       146
#define IDD_FILE_LIST_DIALOG            147
#define IDB_PNG1                        148
#define IDR_FLAG_STRIP_PNG              148
#define IDD_TEST_TASK_DIALOG            149
#define IDD_TEST_MISC_DIALOG            150
#define IDI_MY_TOOL_STRIP_ICON          150
#define IDD_FILE_CHECKSUMS_DIALOG       151
#define IDI_MY_TOOL_STRIP_ALPHA_ICON    151
#define IDD_BUDDY_CONTROLS_DIALOG       152
#define IDC_OPEN_DIALOG_BUTTON          1000
#define IDC_OPEN_PROPERTIES_BUTTON      1001
#define IDC_CREATE_PROPERTIES_BUTTON    1002
#define IDC_DISABLE_THEMES_TOGGLE       1003
#define IDC_DISABLE_SMOOTH_RESIZE_TOGGLE 1004
#define IDC_FORMAT_COMBO                1005
#define IDC_DROP_RIGHT_ARROW_STATIC     1006
#define IDC_SEQ_COUNTER_LABEL           1007
#define IDC_SEQ_COUNTER_EDIT            1008
#define IDC_SEQ_COUNTER_RESET_BUTTON    1009
#define IDC_DETAIL_SHEET_STATIC         1010
#define IDC_SOURCE_FILES_GROUP          1011
#define IDC_COPY_SOURCE_PATHS_BUTTON    1012
#define IDC_FORMAT_LEGEND_LABEL         1013
#define IDC_DESTINATION_FILES_GROUP     1014
#define IDC_PASTE_FILES_BUTTON          1015
#define IDC_CLEAR_FILES_BUTTON          1016
#define IDC_CAPITALIZE_BUTTON           1017
#define IDC_REPLACE_FILES_BUTTON        1019
#define IDC_REPLACE_DELIMS_BUTTON       1020
#define IDC_DELIMITER_SET_COMBO         1021
#define IDC_DELIMITER_STATIC            1022
#define IDC_NEW_DELIMITER_EDIT          1023
#define IDC_FILE_RENAME_LIST            1025
#define IDC_ALBUMS_GROUP                1026
#define IDC_SOURCE_GROUP                1027
#define IDC_SOURCE_LABEL                1028
#define IDC_SOURCE_EDIT                 1029
#define IDC_SOURCE_COMBO                1030
#define IDC_DEST_GROUP                  1031
#define IDC_DEST_LABEL                  1032
#define IDC_DEST_EDIT                   1033
#define IDC_DEST_COMBO                  1034
#define IDC_A_GROUP                     1035
#define IDC_BUTTON1                     1036
#define IDC_BUTTON2                     1037
#define IDC_BUTTON3                     1038
#define IDC_B_GROUP                     1039
#define IDC_BUTTON4                     1040
#define IDC_BUTTON5                     1041
#define IDC_BUTTON6                     1042
#define IDC_DROP_DOWN_STATIC            1044
#define IDC_IMAGE_PATH_COMBO            1045
#define IDC_FRAME_POS_LABEL             1046
#define IDC_FRAME_POS_EDIT              1047
#define IDC_FRAME_COUNT_STATIC          1048
#define IDC_IMAGE_API_COMBO             1049
#define IDC_FORCE_RESOLUTION_LABEL      1050
#define IDC_FORCE_RESOLUTION_COMBO      1051
#define IDC_BK_COLOR_COMBO              1052
#define IDC_ZOOM_COMBO                  1053
#define IDC_STACKING_COMBO              1054
#define IDC_SPACING_EDIT                1055
#define IDC_STATUS_ALPHA_EDIT           1056
#define IDC_SAMPLE_MODE_SHEET           1057
#define IDC_SHOW_COLOR_TABLE_CHECK      1058
#define IDC_SHOW_GUIDES_CHECK           1059
#define IDC_SHOW_LABELS_CHECK           1060
#define IDC_IMAGE_INFO_STATIC           1065
#define IDC_IMAGE_SAMPLE                1066
#define IDC_PIXEL_COLOR_SAMPLE          1067
#define IDC_PIXEL_INFO_STATIC           1068
#define IDC_COLOR_TABLE_MODE_COMBO      1069
#define IDC_COLOR_TABLE_SAMPLE          1070
#define IDC_COLOR_TABLE_INFO_STATIC     1071
#define IDC_UNIQUE_COLORS_CHECK         1072
#define IDC_SHOW_COLOR_LABELS_CHECK     1073
#define IDC_COLOR_TABLE_LABEL           1075
#define IDC_TRANSP_COLOR_SAMPLE         1077
#define IDC_TRANSP_COLOR_INFO           1078
#define IDC_TRANSP_COLOR_LABEL          1079
#define IDC_CHANNEL1_EDIT               1080
#define IDC_CHANNEL2_EDIT               1081
#define IDC_CHANNEL3_EDIT               1082
#define IDC_KEEP_EQUAL_CHECK            1083
#define IDC_FORCE_CVT_EQUAL_BPP_CHECK   1084
#define IDC_FORCE_CVT_COPY_PIXELS_CHECK 1085
#define IDC_RUN_IMAGE_TESTS             1086
#define IDC_USE_ALTERNATE_ROWS_CHECK    1087
#define IDC_USE_TEXT_EFFECTS_CHECK      1088
#define IDC_FILE_STATE_LIST             1089
#define IDC_USE_DIFFS_CHECK             1090
#define IDC_FILE_STATE_EX_LIST          1090
#define IDC_USE_EXPLORER_THEME_CHECK    1091
#define IDC_USE_DEFAULT_DRAW_CHECK      1092
#define IDC_TASK_DIALOG_USAGE           1092
#define IDC_USE_DEFAULT_DRAW_CHECK2     1093
#define IDC_USE_DBG_GUIDES_CHECK        1093
#define IDC_OUTCOME_STATIC              1093
#define IDC_USE_DOUBLEBUFFER_CHECK      1094
#define IDC_FILE_CHECKSUMS_LIST         1095
#define IDC_CALC_CHECKSUMS_BUTTON       1096
#define IDC_SEARCH_PATH_COMBO           1097
#define IDC_FIND_FILES_BUTTON           1098
#define IDC_FOLDER_PATH_COMBO           1099
#define IDC_VERT_SPLITTER_STATIC        1100
#define IDC_HORIZ_SPLITTER_STATIC       1101
#define IDC_SEL_FILE_EDIT               1102
#define IDC_SEL_FILE_PROGRESS           1103
#define ID_COMMAND_LINK1                2001
#define ID_COMMAND_LINK2                2002
#define ID_RADIO_BUTTON1                2101
#define ID_RADIO_BUTTON2                2102
#define IDS_OLE_INIT_FAILED             5000
#define IDS_CHANGE_CASE_TAGS            5001
#define IDC_STRIP_BAR_5                 28510
#define ID_STUDY_IMAGE                  32772
#define ID_CHANGE_CASE                  32773
#define ID_SEND_TO_CLIPBOARD            32774
#define ID_STUDY_LIST_DIFFS             32775
#define ID_NUMERIC_SEQUENCE             32776
#define ID_NUMERIC_SEQUENCE_2DIGITS     32777
#define ID_NUMERIC_SEQUENCE_3DIGITS     32778
#define ID_NUMERIC_SEQUENCE_4DIGITS     32779
#define ID_NUMERIC_SEQUENCE_5DIGITS     32780
#define ID_WILDCARD                     32781
#define ID_EXTENSION_SEPARATOR          32782
#define ID_DROP_RIGHT                   32783
#define ID_DROP_DOWN                    32784
#define ID_DROP_LEFT                    32785
#define ID_DROP_UP                      32786
#define ID_RESOLUTION_TOGGLE            32787
#define ID_ZOOM_TOGGLE                  32788
#define ID_SET_TRANSP_COLOR             32789
#define ID_SET_AUTO_TRANSP_COLOR        32790
#define ID_RESET_TRANSP_COLOR           32791
#define ID_AUTO_TRANSP_TOOL             32792
#define ID_STUDY_TASK_DIALOG            32793
#define ID_STUDY_MISC_DIALOG            32794
#define ID_STUDY_FILE_CHECKSUM          32795
#define ID_STUDY_BUDDY_CONTROLS         32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1104
#define _APS_NEXT_SYMED_VALUE           5002
#endif
#endif
